# Generated by Django 4.1.7 on 2023-04-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1',
        ),
    ]
