# Generated by Django 4.1.7 on 2023-03-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp7', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='mno',
            field=models.IntegerField(),
        ),
    ]
