# Generated by Django 4.1.7 on 2023-04-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('eid', models.IntegerField(unique=True)),
                ('eaddress', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=20)),
                ('eaddress', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
